### ISSUE TITLE
How can I get version 3.0 or 3.1?

### ISSUE THREAD

**Issue by Greater-Gold** [mingodad/picat#3]
I'm trying replay some benchmarks from the MiniZinc Challenge with OR-Tools and PicatSAT, I've doing everything right (at least for my perspective) but I have no luck yet. I think it might be the version I'm using of picat (3.4) since the library https://github.com/nfzhou/fzn_picat was made 2 years ago.

Thanks!

**Comment by hakank** [comment]
@Git-Fanfo What problems do you have running the PicatSAT solver on the MiniZinc Challenge models?

I just tested the PicatSAT solver from the https://github.com/nfzhou/fzn_picat repo  using Picat 3.4#1 (and MiniZinc version 2.7.4) on the 2022 Challenge problems without any issues. (The PicatSAT repo was updated 9 months ago so it's quite current.)

Perhaps it's a problem with the setup of the solver? I wrote about the setup here: https://groups.google.com/g/minizinc/c/mBmQL6gXKP0   

Note that I'm running on a Linux Ubuntu machine so you might have to change some things.

**Comment by hakank** [comment]
I now noticed that you also asked this on the Picat group: https://groups.google.com/g/picat-lang/c/f2QZYwqKQOg/m/iDFSIBlEAgAJ?utm_medium=email&utm_source=footer

Let's continue the discussion there.
